name: "Deploy Production"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
env:
  APP_NAME: "gitops-demo-backend"
  NAMESPACE: "cnc-prod"
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Build and push container"
        run: |-
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}"
          IMAGE_TAG="${GITHUB_REF#refs/*/}"

          docker build -f docker/prod.Dockerfile -t "${IMAGE_NAME}:${IMAGE_TAG}" .
          docker push "${IMAGE_NAME}:${IMAGE_TAG}"

